- .github/workflows/codeql.yml
> feat: Added a config file for codeql

- apps/website/package.json
- pnpm-lock.yaml
> fix: Dependabot/npm and yarn/vite 6.2.5 in dev

- apps/api/controllers/HospitalControllers.js
- apps/api/controllers/WebController.js
- apps/api/controllers/addDepartmentController.js
- apps/api/controllers/webAppointment.js
- apps/api/main.js
- apps/api/routes/HospitalRoutes.js
- apps/api/routes/authRoutes.js
- apps/api/utils/DepartmentFhirHandler.js
- apps/api/utils/DoctorsHandler.js
- apps/api/utils/HospitalFhirHandler.js
- apps/api/utils/WebAppointmentHandler.js
- apps/website/index.html
- apps/website/src/App.jsx
- apps/website/src/Components/ActionsTable/ActionsTable.jsx
- apps/website/src/Components/DocterWiseAppoint/DocterWiseAppoint.jsx
- apps/website/src/Pages/Add_Department/Add_Department.jsx
- apps/website/src/Pages/Appointment/page.jsx
- apps/website/src/Pages/CheckIn/CheckIn.jsx
- apps/website/src/Pages/DepartmentsMain/page.jsx
- apps/website/src/Pages/SignIn/SignIn.jsx
- apps/website/src/main.jsx
- apps/website/src/profileApis/Api.jsx
- apps/website/src/utils/DepartmentFHIRMapper.js
- apps/website/src/utils/FhirMapper.js
Appointment Management and Department module APIs are implemented in a custom/regular format. This made integration with standard healthcare systems and interoperability more difficult.
The Appointment Management and Department module APIs have been successfully updated to follow the FHIR (Fast Healthcare Interoperability Resources) standard.
These changes have also been implemented and integrated into the website.
Appointment data is now structured using the FHIR Appointment resource.
Department data is converted into FHIR-compatible format using HealthcareService and related resources.
The frontend has been updated to handle the new FHIR-based API structure.
#88 
API response and request formats are now in FHIR format.
All frontend components consuming Appointment and …
> Updated AppointmentManagement And Department module in FHIR standard

- apps/website/src/Pages/Add_Vet/Add_Vet.jsx
- apps/website/src/Pages/SignUpDetails/SignUpDetails.css
- apps/website/src/Pages/SignUpDetails/SignUpDetails.jsx
Previously, all the profile details were displayed on a single page, with all the sections shown together without any separation or navigation.
The profile completion flow has been redesigned using tabbed navigation. Instead of displaying all details on a single page, the information is now divided into three separate tabs, each representing a specific section. This improves clarity and enhances the user experience by organizing content more effectively.
Fixes #90
> Updated Complete Profile design in SignupDetails

- .github/workflows/codeql.yml
- apps/mobileApp/android/gradle.properties
> fix: Update codeql.yml

- apps/mobileApp/ios/Podfile.lock
- apps/mobileApp/ios/mobileApp.xcodeproj/project.pbxproj
- apps/mobileApp/ios/mobileApp.xcworkspace/contents.xcworkspacedata
- apps/mobileApp/ios/mobileApp/Info.plist
- apps/mobileApp/ios/mobileApp/PrivacyInfo.xcprivacy
- apps/mobileApp/package.json
- pnpm-lock.yaml
The iOS app fails to run due to execution errors. When attempting to install dependencies and run the app, an error is thrown in the terminal, preventing successful launch.
The execution error has been resolved. The iOS app now installs dependencies and runs successfully without throwing errors during the runtime process.
Fixes #102 
<!-- 
> fix: Resolved iOS App Running Error

- apps/api/controllers/HospitalControllers.js
- apps/api/controllers/InventoryController.js
- apps/api/controllers/WebController.js
- apps/api/controllers/addDepartmentController.js
- apps/api/controllers/addDoctorController.js
- apps/api/controllers/webAppointment.js
- apps/api/models/WebAppointment.js
- apps/api/routes/HospitalRoutes.js
- apps/api/routes/addDoctorsRoutes.js
- apps/api/utils/DoctorsHandler.js
- apps/api/utils/HospitalProfileHandler.js
- apps/website/src/Components/ActionsTable/ActionsTable.jsx
- apps/website/src/Pages/Appointment/page.jsx
- apps/website/src/Pages/Dashboard/page.jsx
- apps/website/src/Pages/Doctor_Dashboard/Doctor_Dashboard.jsx
- apps/website/src/Socket/Socket.jsx
- apps/website/src/profileApis/Api.jsx
- apps/website/src/utils/FhirMapper.js
The API does not sanitize IDs before querying the database, which can lead to potential security issues.
The doctor dashboard is currently implemented using a custom, non-standard data format, making integration with other healthcare systems difficult.
- Implemented ID sanitization in the API layer to ensure secure database access.
- Migrated the doctor dashboard to follow FHIR standards using resources like Practitioner and Appointment.
Fixes #109
> Feat:sanitize API IDs and migrate doctor dashboard to FHIR standard

- .github/workflows/codeql.yml
> fix: Update CodeQl YAML

- apps/api/controllers/medicalRecords.js
- apps/api/middlewares/upload.js
- apps/api/models/medical.js
- apps/api/routes/user.js
- apps/api/services/FHIRMedicalRecordService.js
The medical records API was not FHIR compliant.
The API now supports FHIR-compliant requests and responses for adding and retrieving medical records.
Fixes #100 
<!-- 
> feat: add and get medical records using FHIR compliance

- apps/api/controllers/ListController.js
- apps/api/routes/user.js
- apps/api/services/DoctorService.js
- The API returns a list of doctors in a custom JSON structure.
- Fields are typically flat and app-specific (e.g., name, specialization, hospital_id, etc.).
- Lacks standardization, which makes integration with external systems or health apps harder.
- The API now returns data in accordance with the HL7 FHIR specification, specifically using the Practitioner and possibly PractitionerRole resources.
- Includes structured fields like name, telecom, qualification, identifier, etc.
- Improved interoperability with EHRs, healthcare apps, and health information exchanges.
Fixes #101 
<!-- 
> Updated get doctors list api to FHIR Compliance

- apps/api/controllers/SlotController.js
- apps/api/routes/user.js
- apps/api/services/DoctorService.js
- apps/api/services/MonthlySlotService.js
- API throws a validation error even when a valid Doctor Id is provided.
- The request fails with an error like "Doctor Id is invalid" .
- The system does not proceed to create or update the appointment due to this error.
- API correctly accepts valid Doctor Ids.
- No validation errors are thrown when a proper ID is sent in the request.
- Invalid or missing Doctor Ids are still rejected as expected, maintaining data integrity.
Fixes #201 
<!-- 
> Validation for Doctor Id

- apps/api/controllers/ListController.js
- apps/api/controllers/SlotController.js
- apps/api/routes/user.js
- apps/api/services/DoctorService.js
When fetching the list of doctors and their time slots, only the MongoDB ObjectId (i.e., _id) of the doctor is being returned.
- The doctorId appears as just the raw ObjectId.
- Other real details like doctor’s name, specialization, etc., are not included.
Now API return the complete doctor details (or at least selected fields like name, specialization, etc.) along with the time slots.
Fixes #204 
<!-- 
> Fix: fixed doctor Id issue and time slots in getTimeslots Api and DoctorList API

- apps/api/controllers/ApiAdminControllers.js
- apps/api/controllers/HospitalControllers.js
- apps/api/controllers/InventoryController.js
- apps/api/middlewares/authMiddleware.js
- apps/api/models/AddInventoryCotegory.js
- apps/api/routes/AdminControllerRoutes.js
- apps/api/routes/HospitalRoutes.js
- apps/api/routes/InventoryRoutes.js
- apps/api/utils/HospitalFhirHandler.js
- apps/api/utils/InventoryFhirHandler.js
- apps/website/package.json
- apps/website/src/App.jsx
- apps/website/src/Components/ActionsTable/ActionsTable.jsx
- apps/website/src/Components/UplodeImage/UplodeImage.jsx
- apps/website/src/Pages/AddInventory/AddInventory.jsx
- apps/website/src/Pages/AddProcedurePackage/AddProcedurePackage.jsx
- apps/website/src/Pages/AddProcedurePackage/ViewProcedurePackage.jsx
- apps/website/src/Pages/Add_Vet/Add_Vet.jsx
- apps/website/src/Pages/Appointment/page.jsx
- apps/website/src/Pages/Dashboard/page.jsx
- apps/website/src/Pages/DoctorProfile/DoctorProfile.jsx
- apps/website/src/Pages/Inventory/Inventory.jsx
- apps/website/src/Pages/SignUpDetails/SignUpDetails.jsx
- apps/website/src/index.css
- apps/website/src/services/apiService.js
- apps/website/src/utils/InventoryFHIRMapper.js
- pnpm-lock.yaml
The Procedure Package module follows a custom standard.
The Procedure Package module now adheres to the FHIR standard.
Fixes #115 #116 #117
> Update Inventory & procedurePackage module in fhir standard

- apps/api/controllers/assessmentsController.js
- apps/api/models/assessments.js
- apps/api/routes/apiRoutes.js
- apps/api/services/assessmentService.js
- apps/website/src/Components/ActionsTable/AssessmentsTable.jsx
- apps/website/src/Pages/AssessmentManagement/AssessmentManagement.jsx
- apps/website/src/utils/FhirDataConverter.js
The confirm, completed, cancelled assessment was static
The confirm, completed, cancelled assessment is now dynamic
Fixes #159
> feat: In assessment module integrate Api with filter

- apps/api/controllers/ApiAdminControllers.js
- apps/api/controllers/HospitalControllers.js
- apps/api/controllers/InventoryController.js
- apps/api/controllers/addDoctorController.js
- apps/api/controllers/webAppointment.js
- apps/api/main.js
- apps/api/middlewares/authMiddleware.js
- apps/api/models/AppointmentOption.js
- apps/api/models/PurposeOfVisit.js
- apps/api/routes/AdminApiRoutes.js
- apps/api/routes/HospitalRoutes.js
- apps/api/utils/DoctorsHandler.js
- apps/website/src/Components/MainHeader/MainHeader.jsx
- apps/website/src/Components/PatientsTable/PatientsTable.jsx
- apps/website/src/Pages/AddInventory/AddInventory.jsx
- apps/website/src/Pages/AddProcedurePackage/AddProcedurePackage.jsx
- apps/website/src/Pages/AddProcedurePackage/ViewProcedurePackage.jsx
- apps/website/src/Pages/Add_Vet/Add_Vet.jsx
- apps/website/src/Pages/Appointment/page.jsx
- apps/website/src/Pages/CheckIn/CheckIn.jsx
- apps/website/src/Pages/Dashboard/page.jsx
- apps/website/src/Pages/Doctor_Dashboard/Doctor_Dashboard.jsx
- apps/website/src/Pages/Inventory/Inventory.jsx
- apps/website/src/Pages/SignUpDetails/SignUpDetails.jsx
- apps/website/src/services/apiService.js
- apps/website/src/utils/FhirMapper.js
The feedback modules use static data.
The feedback modules now use dynamic data and follow the FHIR standard.
Fixes #217
> Create and integrate feedback api in feedback-module

- apps/api/controllers/ListController.js
- apps/api/routes/user.js
- apps/api/services/BusinessService.js
- apps/api/services/DoctorService.js
- apps/api/services/MonthlySlotService.js
- apps/api/utils/BusinessFhirFormatter.js
- The Get List API returns facility data in a custom JSON format, specific to internal requirements.
- Facility types (e.g., hospital, clinic, pet sitter) are represented as simple strings or IDs.
- No standard coding system (like SNOMED or HL7) is used.
- Lacks interoperability with external healthcare/pet care systems.
- Minimal filtering and metadata support.
- The API now returns data in FHIR-compliant format, using the Organization resource.
- Facility types are coded using standardized FHIR type.coding.
- Supports query parameters for filtering (e.g., type=hospital)
- Returns a proper FHIR Bundle with metadata (resourceType, type, and entry[]).
- Pagination and extension support added.
Fixes #227 
<!-- 
> Feat. updated get list API for Hospital, Clinic, Breeding Facility, Pet Sitter, Groomer Shop to FHIR Compliance

- apps/api/controllers/ListController.js
- apps/api/controllers/PetController.js
- apps/api/controllers/authController.js
- apps/api/models/vaccination.js
- apps/api/services/BusinessService.js
- apps/api/services/ImmunizationService.js
- apps/api/services/PetService.js
- apps/api/utils/BusinessFhirFormatter.js
- apps/api/utils/ImmunizationMapper.js
- The hospital API response does not include the departments field.
- This leads to incomplete data for consumers of the API .
- CodeQL analysis may report potential issues such as invalidated input, Database query built from user-controlled sources.
- The hospital API response now correctly includes a departments array with relevant department data.
- he relationship between hospitals and departments is properly resolved and populated.
- CodeQL issues have been addressed.
Fixes #231 
<!-- 
> Fixed hospital array to show department List and other CodeQL Fixes

- apps/website/src/Pages/Appointment/page.jsx
- apps/website/src/Pages/SignIn/SignIn.css
- apps/website/src/Pages/SignIn/SignIn.jsx
- apps/website/src/Pages/SignUp/SignUp.css
- apps/website/src/Pages/SignUp/SignUp.jsx
- apps/website/src/index.css
The SignIn and SignUp pages were using outdated layouts and lacked proper form validation.  
They were not fully responsive on mobile devices and didn't follow the latest design system.
- Updated the layout and design of SignIn and SignUp pages
- Added client-side validation for email and password fields
- Improved mobile responsiveness with flexible styling
- Optimized component structure for readability
- Applied new design system components (buttons, inputs)
Fixes #233
>  Update SignUp & SignIn Page

- apps/website/src/Pages/SignUpDetails/SignUpDetails.css
- apps/website/src/Pages/SignUpDetails/SignUpDetails.jsx
- apps/website/src/index.css
- The Signup Details page lacks proper validation for required fields such as "Full Name," "Email," and "Department Selection."
- User selections (e.g., chosen departments) are lost when navigating between steps of the signup process.
- UI elements are misaligned on smaller screen sizes (e.g., mobile view).
- Form fields now validate input before allowing the user to proceed.
- Selected data is persisted across steps using React Context.
- Improved error handling and display of feedback messages when fields are incomplete.
Fixes #238
> Update Signup Details Page

- apps/api/controllers/ListController.js
- apps/api/routes/user.js
- apps/api/services/AppointmentService.js
- apps/api/services/BusinessService.js
- apps/api/utils/enrichmentHelpers.js
1. **Search Organization API:**
- There is no dedicated API for searching organizations.
- Users need to manually sift through organization data, which is inefficient and may not provide filtering options based on specific criteria like name, location, etc.
2. **Appointment List API:**
- The returned data from the Appointment List API is incomplete and doesn't include all necessary details.
- Essential information like **organization names**, **patient details**, and **timestamps** might be missing, making it difficult for clients to display the full context of appointments.
1. **Search Organization API:**
- A new API endpoint will be added to allow users to search **organizations** by name, **location**, or other relevant filters.
- The API will enable users to filter and sort …
> Feature & Fix: Search Organization API and Updated Appointment List Response

- .gitignore
- apps/api/eslint.config.js
- apps/api/package.json
- packages/types/package.json
- packages/types/tsconfig.json
- pnpm-lock.yaml
> fix: Added eslint to API

- apps/api/routes/NewsletterRoutes.js
> fix: Fixed error in Newsletter route

- apps/api/package.json
- apps/api/tsconfig.json
- pnpm-lock.yaml
> fix: Updated tsconfig in API to work independently

- apps/api/controllers/NewsletterController.js
- apps/api/routes/NewsletterRoutes.js
> fix: Fixed Unsubscribe API route

- apps/api/main.ts
- packages/types/package.json
- packages/types/src/aws.ts
- packages/types/src/index.ts
- pnpm-lock.yaml
> fix: resolved typescript errors in main.ts

- .gitignore
- package.json
- packages/types/package.json
- packages/types/tsconfig.build.json
- packages/types/tsconfig.json
> feat: Convert types to compiled package

- apps/frontend/src/app/(routes)/notificationpage/page.tsx
- apps/frontend/src/app/Components/DataTable/PracticeTeamTable.tsx
- apps/frontend/src/app/Pages/NotificationPage/NotificationPage.css
- apps/frontend/src/app/Pages/NotificationPage/NotificationPage.tsx
- apps/frontend/src/app/Pages/RevenueManagement/RevenueManagement.css
- apps/frontend/src/app/Pages/RevenueManagement/RevenueManagement.tsx
Currently, the application does not have a centralized notification page. Users can only see recent alerts via the header dropdown, and once dismissed, these notifications cannot be retrieved or reviewed again.
- Introduced a new Notification Page accessible via the dashboard/navigation.
- Displays a list of all user/system notifications.
- Each notification includes:
- Title
- Message
- Timestamp
- Read/Unread indicator
- Added functionalities:
- Mark notifications as read/unread
- Filter notifications by category/type
- Clear all or selected notifications
- Responsive UI with consistent design language across the application.
Fixes #351
> feat: notification page

- apps/api/controllers/BlogController.ts
- apps/api/main.ts
- apps/api/models/AddBlog.ts
- apps/api/routes/BlogApiRoutes.ts
- apps/frontend/src/app/Pages/BlogPage/CreateBlog.tsx
Previously this page was static , there is no apis exists of this page 
Now APIs of this blog page is created and Frontend is also dynamic with validations and api integrations .
Fixes #378
> created blog page and created blog apis

- apps/api/controllers/auth-controller.ts
- apps/frontend/src/app/Pages/CompleteProfile/CompleteProfile.tsx
- packages/types/src/index.ts
The Complete Business Profile section only displayed static UI. No data was fetched or saved using API calls.
API integration has been successfully implemented. The Complete Business Profile section now fetches and submits data through the backend, making it fully functional.
Fixes #384
> Complete Business Profile: API Integration and Functional Implementation

- apps/frontend/src/app/(routes)/businessDashboard/page.tsx
- apps/frontend/src/app/Pages/CompleteProfile/CompleteProfile.tsx
- apps/frontend/src/app/Pages/InviteTeamMembers/InviteTeamMembers.tsx
> fix: Resolved more type errors

- .npmrc
> fix: Updated npmrc for nextjs amplify

- apps/api/controllers/AddDoctorController.ts
- apps/api/controllers/WebController.ts
- apps/api/controllers/invite-teams-members.ts
- apps/api/main.ts
- apps/api/routes/AddDoctorsRoutes.ts
- apps/frontend/next.config.ts
- apps/frontend/package.json
- apps/frontend/src/app/Components/DynamicSelect/DynamicSelect.tsx
- apps/frontend/src/app/Components/Header/Header.tsx
- apps/frontend/src/app/Components/OperatingHours/OperatingHours.tsx
- apps/frontend/src/app/Components/SessionInitializer.tsx
- apps/frontend/src/app/Components/UploadImage/UploadImage.tsx
- apps/frontend/src/app/Pages/AddVetProfile/AddVetProfile.tsx
- apps/frontend/src/app/Pages/CompleteProfile/CompleteProfile.tsx
- apps/frontend/src/app/Pages/Sign/SignIn.tsx
- apps/frontend/src/app/stores/authStore.ts
- apps/frontend/src/app/utils/Api/profileApi.tsx
- packages/fhir/src/complete-vet-profile/complete-vet-profile.ts
- packages/fhir/src/hospital-profile-fhir.ts
- packages/types/src/AddDoctor/add.doctor.types.ts
- packages/types/src/complete-vet-profile/complete-vet-profile.ts
- pnpm-lock.yaml
The current implementation of addVetProfiles, businessProfile, and inviteTeamsApi does not fully align with the latest FHIR structure.
- operatingHours are inconsistently handled (incorrect casing or not stringified).
- uploadedFiles and image data are not properly formatted in FHIR extensions.
- inviteTeamsApi lacks updated validation and structure for department, role, and invite code fields.
- Type safety is weak or inconsistent across modules.
- Updated addVetProfiles to support FHIR-compliant structure for operatingHours, duration, image, and certificates.
- Refactored businessProfile to match the latest Organization-based FHIR structure.
- Improved inviteTeamsApi to use standardized input types and ensure correct mapping for invitations (including department, role, invite code).
- …
> Fix and Align addVetProfiles, businessProfile, and inviteTeamsApi with New FHIR Model

- apps/api/controllers/AddDepartmentController.ts
- apps/api/controllers/HospitalControllers.ts
- apps/api/models/AddDepartment.ts
- apps/api/routes/AuthRoutes.ts
- apps/frontend/src/app/Components/Services/DepartmentHeadSelector/DepartmentHeadSelector.tsx
- apps/frontend/src/app/Components/Services/ServicesSelection/ServicesSelection.tsx
- apps/frontend/src/app/Pages/Departments/AddDepartments.tsx
- packages/fhir/src/addSpecialities/specialities-fhir.ts
- packages/fhir/src/index.ts
- packages/types/src/Departments/DepartmentTypes.ts
- packages/types/src/index.ts
Add Department Page is static there is not any type of functionalities exist. 
Now page is dynamic with proper validations .
updated the api of add department added more validations in it , Created fhir functions for sending responses .
Fixes #419
> Add Department page 

- apps/api/config/connect.ts
- apps/api/controllers/WebController.ts
- apps/api/middlewares/authMiddleware.ts
Users were unable to log in on the live server. Despite providing valid credentials, the authentication process was failing, preventing access to protected routes or dashboard features.
Login now works as expected on the live server. Users can successfully authenticate and maintain sessions, resolving the issue that was previously blocking access.
Fixes #429
> Fix login problem

- apps/frontend/src/app/(routes)/clientstatementdashboard/page.tsx
- apps/frontend/src/app/Components/DataTable/ClientStatementsTable.tsx
- apps/frontend/src/app/Components/DataTable/DataTable.css
- apps/frontend/src/app/Components/DataTable/ManageBillingTable.tsx
- apps/frontend/src/app/Pages/ClientStatements/ClientStatements.css
- apps/frontend/src/app/Pages/ClientStatements/ClientStatementsDashboard.tsx
- apps/frontend/src/app/Pages/ClientStatements/ClientStatementsDetails.tsx
- apps/frontend/src/app/Pages/DoctorDashboard/DoctorDashboard.css
- apps/frontend/src/app/Pages/DoctorDashboard/DoctorDashboard.tsx
Currently, the Client Statements Dashboard provides a basic view with limited information and functionality. Users can only view statement records in a static list without filters, search, or actionable options such as downloading or emailing statements. The interface lacks visual clarity, and the absence of sorting or categorization makes it difficult to manage large datasets efficiently.
The updated dashboard will include the following improvements:
- Search and filter functionality by client name, date range, status, and statement type.
- Improved table layout with columns for: Client Name, Statement Period, Date Issued, Status, and Actions.
- Action buttons to download PDF, email statement, or view full details.
- Responsive design for better usability across devices.
- Bulk actions …
>  Update Client Statements Dashboard

- apps/frontend/src/app/(routes)/managediscounts/page.tsx
- apps/frontend/src/app/Components/DataTable/ManageDiscountTable.tsx
- apps/frontend/src/app/Pages/ManageDiscounts/ManageDiscounts.css
- apps/frontend/src/app/Pages/ManageDiscounts/ManageDiscounts.tsx
Currently, the Manage Discount Page offers only basic functionalities such as viewing a list of discounts and limited editing capabilities. There is no support for filtering discounts, applying bulk actions, or setting advanced rules like minimum order value or applicable customer groups. Additionally, the UI is not fully optimized for usability or responsiveness.
The updated Manage Discount Page will include:
- Enhanced UI with table sorting, filtering, and pagination.
- Ability to search discounts by name, code, or status.
- Option to create advanced discount rules (e.g., minimum purchase, first-time users only).
- Improved form to add/edit discounts with the following fields:
- Discount Code/Name
- Type (Percentage / Flat)
- Value
- Start & End Date
- Usage Limit (per user / total)
- …
> Update Manage Discount Page

- apps/api/controllers/details-controller.ts
- apps/api/controllers/medical-records-controller.ts
- apps/api/models/breeder-details.ts
- apps/api/models/pet-boarding.ts
- apps/api/models/pet-groomer.ts
- apps/api/models/vet-clinic.ts
- apps/api/services/monthly-slot-service.ts
- apps/api/utils/fhir-utils.ts
- packages/fhir/src/details/boarding-fhir.ts
- packages/fhir/src/details/breeder-fhir.ts
- packages/fhir/src/details/fhir-organization-validator.ts
- packages/fhir/src/details/groomer-fhir.ts
- packages/fhir/src/index.ts
- packages/fhir/src/slots-fhir.ts
- packages/types/src/index.ts
- packages/types/src/models/pet-boarding.ts
- packages/types/src/models/pet-groomer.ts
- packages/types/src/models/vet-clinic.ts
- The APIs for Pet Groomer, Pet Boarding, and Pet Owner are currently written in JavaScript.
- There is no static type checking, which increases the risk of runtime errors.
- Lack of type-safe contracts makes API development and consumption more error-prone.
- All pet-related modules will be refactored to use TypeScript:
1. Interfaces or types will be defined for Pet, Owner, GroomingService, BoardingService, etc.
2. Route handlers, middlewares, and services will have typed parameters and return types.
3. Error handling and input validation will become stricter and more predictable.
Fixes #447 
<!-- 
> Feature Request: Convert Pet-Related APIs to TypeScript

- apps/frontend/src/app/(routes)/resources/page.tsx
- apps/frontend/src/app/Components/Header/Header.css
- apps/frontend/src/app/Pages/Resources/Resources.css
- apps/frontend/src/app/Pages/Resources/Resources.tsx
Currently, there is no dedicated Resources page in the application. Users must navigate across various sections or rely on external documentation to find help, support content, or downloadable assets. This fragmented experience can lead to confusion and increased support requests.
A new "Resources" page will be added to the platform. It will:
- Display categorized content such as Documentation, FAQs, Tutorials, Downloads, and External Links.
- Allow users to search and filter resources efficiently.
- Offer a structured layout that is easy to navigate and update.
- Optionally support tagging, file uploads, and feedback/comments on resources.
Fixes #479
> Create New Resources Page

- apps/frontend/package.json
- apps/frontend/src/app/(routes)/businessDashboard/page.tsx
- apps/frontend/src/app/(routes)/signin/page.tsx
- apps/frontend/src/app/(routes)/signup/page.tsx
- apps/frontend/src/app/Components/Header/Header.tsx
- apps/frontend/src/app/Pages/Sign/SignUp.tsx
- pnpm-lock.yaml
Pages are public , No private routing exists .
Created layouts and checks and added private routing .
Fixes #483
> fix: private routing

- apps/frontend/src/app/(routes)/procedurepackage/page.tsx
- apps/frontend/src/app/Components/DataTable/AddItemsTable.tsx
- apps/frontend/src/app/Pages/Inventory/AddInventory/AddInventory.css
- apps/frontend/src/app/Pages/Inventory/AddInventory/AddInventory.tsx
- apps/frontend/src/app/Pages/Inventory/InventoryDetails/InventoryDetails.css
- apps/frontend/src/app/Pages/Inventory/InventoryDetails/InventoryDetails.tsx
- apps/frontend/src/app/Pages/Inventory/ProcedurePackage/ProcedurePackage.css
- apps/frontend/src/app/Pages/Inventory/ProcedurePackage/ProcedurePackage.tsx
- apps/frontend/src/app/globals.css
- apps/website/src/Pages/Add_Vet/Add_Vet.jsx
- apps/website/src/index.css
Currently, the inventory module has basic functionality and limited UI/UX. Some pages may be incomplete, missing validations, or lacking advanced features such as filtering, editing, or dynamic data binding. There may also be UI inconsistencies or outdated layouts.
The updated inventory pages will include:
- Improved Inventory List Page with filters, search, and pagination.
- Updated Edit Inventory Page to support validation, real-time updates, and better UX.
- Enhanced Add Inventory Page with error handling, dropdowns (for categories/suppliers), and responsive design.
- Integration with backend APIs for seamless CRUD operations.
- UI updates using consistent styles and reusable components.
Fixes #486
> Update Inventory Some Pages

- apps/api/controllers/auth-controller.ts
- apps/api/controllers/immunization-controller.ts
- apps/api/controllers/list-controller.ts
- apps/api/controllers/medical-records-controller.ts
- apps/api/package.json
- apps/api/routes/AuthRoutes.ts
- apps/api/services/google-auth-service.ts
- packages/fhir/src/business-fhir/business-formatter-fhir.ts
- packages/fhir/src/immunization/immunization-fhir.ts
- packages/types/src/business-formatter-types/business-formatter-types.ts
- packages/types/src/immunization/immunization-types.ts
- pnpm-lock.yaml
There were type errors in the current implementation, and the backend integration was not aligned with the Figma design specifications, causing issues with smooth integration.
The type errors have been fixed, and changes have been made to ensure that the backend is aligned with the Figma design, enabling seamless integration.
Fixes #500
> Medical record modification

- apps/api/controllers/AddDoctorController.ts
- apps/api/controllers/HospitalControllers.ts
- apps/api/controllers/WebAppointment.ts
- apps/api/models/web-appointment.ts
- apps/api/routes/AddDoctorsRoutes.ts
- apps/api/routes/AppointmentRoutes.ts
- apps/api/services/appointment-service.ts
- apps/api/services/monthly-slot-service.ts
- apps/api/services/monthly.slot.service.ts
- apps/api/services/slot-service.ts
- apps/frontend/src/app/Components/DataTable/ManageInviteTable.tsx
- apps/frontend/src/app/Components/Header/Header.tsx
- apps/frontend/src/app/Pages/AddVetProfile/AddVetProfile.tsx
- apps/frontend/src/app/Pages/AppointmentVet/CreateAppointment/CreateAppointment.css
- apps/frontend/src/app/Pages/AppointmentVet/CreateAppointment/CreateAppointment.tsx
- apps/frontend/src/app/Pages/BusinessDashboard/BusinessDashboard.tsx
- apps/frontend/src/app/Pages/DoctorDashboard/DoctorDashboard.tsx
- apps/frontend/src/app/Pages/PracticeTeam/PracticeTeam.tsx
- apps/frontend/src/app/Pages/Sign/SignUp.tsx
- packages/fhir/src/WebAppointments/web-appointments.ts
- packages/fhir/src/index.ts
- packages/types/src/index.ts
- packages/types/src/models/appointments.model.ts
- packages/types/src/web-appointments-types/web-appointments.ts
The Create Appointment module had no API integration, and its functionality was non-operational.  
Additionally, the Create Appointment API had not been developed.
Developed and implemented the Create Appointment API, and integrated it with the Create Appointment module to enable full functionality.
Fixes #509
> Add create appointment API and integrate into create appointment module

- apps/frontend/src/app/Components/SessionInitializer.tsx
Public Routes are not accessible when user is signout 
Mentioned public routes .
Fixes #518
> fix: Added public routes

- apps/frontend/src/app/(routes)/addprofiledetail/page.tsx
- apps/frontend/src/app/Pages/AddVetProfile/AddProileDetails.tsx
- apps/frontend/src/app/Pages/AddVetProfile/AddVetProfile.css
There is currently no dedicated page or form to add a new veterinarian's profile details. Vet information has to be manually added in the database or through temporary/partial forms, which leads to incomplete, inconsistent, or hard-to-manage vet records.
A new "Add Vet Profile Details" page will be available in the Vet Management section.
This page will:
- Provide a structured form to enter personal, contact, and professional details of a vet.
- Include image upload functionality for the vet's profile picture.
- Validate all required fields before submission.
- Save the entered data to the system database.
- Maintain design consistency with the rest of the dashboard.
Fixes #525
> Create Add Vet Profile Details Page

- apps/api/controllers/auth-controller.ts
- apps/api/controllers/details-controller.ts
- apps/api/controllers/medical-records-controller.ts
- apps/api/models/appuser-model.ts
- apps/api/models/medical-record-folder-model.ts
- apps/api/models/vet-clinic.ts
- apps/api/routes/AppRoutes.ts
- apps/api/routes/AuthRoutes.ts
- apps/api/utils/helpers.ts
- packages/fhir/src/index.ts
- packages/fhir/src/profile/profile-data-fhir.ts
- packages/types/src/HospitalProfile/hospital.profile.model.ts
- packages/types/src/models/IUser.ts
- packages/types/src/models/vet-clinic.ts
Medical record folders could not flexibly aggregate or assign multiple records after creation. There was no efficient way to batch add records to a folder or fetch all records belonging to a folder. Searching for medical records by name was not supported. The code also contained unused debug statements.
Medical record folders now maintain an array of associated medical record ObjectIds, allowing flexible batch assignment and aggregation. New endpoints allow placing multiple records in a folder and fetching all records for a folder, with FHIR conversion for API responses. A search endpoint enables finding records by title. Unused debug statements have been removed for cleaner code.
>  Medical controller modification, user profile api modification

- apps/frontend/src/app/Components/Footer/Footer.tsx
- apps/frontend/src/app/Components/Header/Header.css
- apps/frontend/src/app/Components/TeamSlide/TeamSlide.css
- apps/frontend/src/app/Components/TeamSlide/TeamSlide.tsx
- apps/frontend/src/app/Pages/AboutUs/AboutUs.css
- apps/frontend/src/app/Pages/AboutUs/AboutUs.tsx
- apps/frontend/src/app/Pages/BookDemo/BookDemo.css
- apps/frontend/src/app/Pages/DeveloperLanding/DeveloperLanding.css
- apps/frontend/src/app/Pages/HomePage/HomePage.css
- apps/frontend/src/app/Pages/HomePage/HomePage.tsx
- apps/frontend/src/app/Pages/MainLandingPage/MainLandingPage.css
- apps/frontend/src/app/Pages/MainLandingPage/MainLandingPage.tsx
- apps/frontend/src/app/Pages/PetOwner/PetOwner.css
- apps/frontend/src/app/Pages/PetOwner/PetOwner.tsx
- pnpm-lock.yaml
**What is the current behavior?**
Some components and pages are still using placeholder or outdated text/design. The implementation does not fully match the Figma design, and certain content is missing because it has not yet been provided.
**What is the new behavior?**
The components and pages will be updated with the finalized text, design, and layout based on the Figma file and the content provided by the teamThis ensures the UI is consistent, polished, and aligned with the latest requirements.
Fixes #574
> feat: Update changes

- apps/api/routes/AuthRoutes.ts
Users are experiencing login errors when attempting to sign in.
Fix the login flow to ensure users can authenticate successfully without errors.
Fixes #588
> Fixed Login issue

- apps/api/controllers/api-admin-controller.ts
- apps/frontend/src/app/Components/DataTable/AddItemsTable.tsx
- apps/frontend/src/app/Components/DataTable/DataTable.css
- apps/frontend/src/app/Components/DataTable/ManageInventoryTable.tsx
- apps/frontend/src/app/Components/DataTable/ProcedurePackagesTable.tsx
- apps/frontend/src/app/Pages/AddVetProfile/AddVetProfile.css
- apps/frontend/src/app/Pages/AdminDashboardEmpty/AdminDashboardEmpty.tsx
- apps/frontend/src/app/Pages/Inventory/InventoryDashboard/InventoryDashboard.tsx
- apps/frontend/src/app/Pages/Inventory/ProcedurePackage/ProcedurePackage.css
- apps/frontend/src/app/Pages/Inventory/ProcedurePackage/ProcedurePackage.tsx
- apps/frontend/src/app/Pages/MainLandingPage/MainLandingPage.tsx
- apps/frontend/src/app/globals.css
**What is the current behavior?**
The existing design procedure package is outdated and lacks consistency across modules. It does not follow modern design principles, making it difficult to maintain, scale, and ensure a seamless user experience. Developers often face redundancy and extra effort due to missing standardized components and unclear design guidelines.
**What is the new behavior?**
The updated design procedure package will follow modern UI/UX standards with consistent, reusable components and clear design guidelines. It will improve scalability, reduce development time, and ensure a unified and professional look across all application modules.
Fixes #594
>  Update Design Procedure Package

- apps/api/controllers/AddDoctorController.ts
- apps/frontend/src/app/Pages/AddVetProfile/AddVetProfile.tsx
- Profile picture upload: frontend uploads successfully but backend fails to save image URL due to logical error
- OperatingHours state: updating resets existing values and 'Complete Later' leaves blank state, causing data loss
Profile picture upload: The frontend uploads successfully, but the backend fails to save the image URL due to a logical error. This results in the profile being created without a picture.
OperatingHours state: When updating, it resets existing values. Clicking Complete Later keeps the field blank, causing the existing data to be lost.
Fixed backend logic to correctly save the uploaded profile picture URL with the profile data.
Updated state management for OperatingHours to persist previously set values even after updates or when clicking Complete Later.
Fixes #596
> fix: resolve profile creation issues Profile picture upload | OperatingHours state

- apps/frontend/src/app/Pages/BusinessDashboard/BusinessDashboard.tsx
- The Business Dashboard page is throwing an error.
- Users are unable to view or interact with the dashboard properly.
- Fixed the error in the Business Dashboard page.
- The dashboard now loads correctly and works as expected.
- Improved stability to ensure smooth user experience.
Fixes #601
> Resolve error on Business Dashboard page

- apps/api/controllers/WebAppointment.ts
- apps/api/controllers/invite-teams-members.ts
Invited users are unable to complete the signup process.
Fixed the issue so that invited users can successfully sign up.
Fixes #603
> Register Invited Users

- apps/api/controllers/WebController.ts
- apps/api/controllers/invite-teams-members.ts
- apps/api/routes/AuthRoutes.ts
- apps/api/routes/InviteTeamsMembersRoutes.ts
- apps/frontend/src/app/Components/CommonTabs/CommonTabForPractitioners.tsx
- apps/frontend/src/app/Components/DataTable/PracticeteamtableForBusinessDashboard.tsx
- apps/frontend/src/app/Pages/AddVetProfile/AddProileDetails.tsx
- apps/frontend/src/app/Pages/BusinessDashboard/BusinessDashboard.tsx
- packages/fhir/src/index.ts
- packages/fhir/src/invites-teams/invites-teams.ts
- packages/types/src/InviteTeamsMembers/invite-teams-members.ts
- packages/types/src/index.ts
The practice team table in the business dashboard is static and does not fetch or update data dynamically.  
The practice team table has been updated to be dynamic.  
It now fetches data from the backend and displays real-time team information such as doctors, staff, departments, and their status.  
Fixes #613
> Make Practice Team Table Dynamic in Business Dashboard

- apps/frontend/src/app/Components/Github/Github.css
- apps/frontend/src/app/Components/Github/Github.tsx
- apps/frontend/src/app/Pages/AboutUs/AboutUs.tsx
- apps/frontend/src/app/Pages/MainLandingPage/MainLandingPage.css
- apps/frontend/src/app/Pages/MainLandingPage/MainLandingPage.tsx
- apps/frontend/src/app/Pages/PricingPage/PricingPage.css
- apps/frontend/src/app/Pages/PricingPage/PricingPage.tsx
- apps/frontend/src/app/Pages/PrivacyPolicy/PrivacyPolicy.css
- apps/frontend/src/app/Pages/Sign/SignUp.tsx
- apps/frontend/src/app/globals.css
**What is the current behavior?**
- The consent checkboxes on the Sign Up page are either misaligned, unclear, or not functioning as expected.
- The accompanying consent text (e.g., terms & conditions, privacy policy agreement) is not displayed correctly or is confusing for users.
- Users may not clearly understand what they are agreeing to during signup.
**What is the new behavior?**
Consent checkboxes are properly aligned and styled consistently with the rest of the form.
Each checkbox includes clear, user-friendly text explaining what the user is agreeing to.
Links to related documents (Terms of Service, Privacy Policy) are correctly embedded and clickable.
The checkboxes function correctly, ensuring users must provide consent before completing signup.
Fixes #656 #657
> Fix consent checkboxes and text in Sign up Page

- apps/frontend/src/app/Components/Footer/Footer.tsx
- apps/frontend/src/app/Pages/PricingPage/PricingPage.tsx
- apps/frontend/src/app/Pages/PrivacyPolicy/PrivacyPolicy.css
- apps/frontend/src/app/Pages/PrivacyPolicy/PrivacyPolicy.tsx
- apps/frontend/src/app/Pages/TermsAndConditions/TermsAndConditions.css
- apps/frontend/src/app/Pages/TermsAndConditions/TermsAndConditions.tsx
The privacy policy and terms & conditions page is outdated, missing recent updates, and does not fully align with the latest company policies, compliance requirements, or design standards.
- Updated content of the privacy policy and terms & conditions to reflect current regulations and business practices.
- Improved readability and structure of the page.
- Applied new design styles for better user experience and consistency with the rest of the site.
- Ensured responsive layout across devices.
Fixes #661
> Update privacy policy terms and condition page

- apps/api/package.json
- apps/frontend/package.json
- apps/mobileApp/package.json
- packages/types/package.json
- pnpm-lock.yaml
> fix: Dependant Issues 

- apps/frontend/src/app/Components/Header/Header.tsx
- apps/frontend/src/app/Pages/PricingPage/PricingPage.tsx
> fix: Removed Back Button from Pricing Page

- .github/workflows/sonar-cloud-analysis.yml
- sonar-project.properties
- Currently we don't have any workflow for `sonarqube`.
- This PR adds support for `sonarqube` integration with our current workflows to detect code quality, code smells, test coverage and many more.
Fixes #786
>  Integrate `SonarQube` with GitHub actions

- apps/frontend/src/app/Components/Footer/Footer.tsx
- apps/frontend/src/app/Components/Header/PublicHeader.tsx
- apps/frontend/src/app/Pages/MainLandingPage/MainLandingPage.css
- apps/frontend/src/app/Pages/MainLandingPage/MainLandingPage.tsx
> fix: Landing Page fixes

- apps/frontend/src/app/(routes)/petowner/page.tsx
- apps/frontend/src/app/Components/FAQ/FAQ.css
- apps/frontend/src/app/Components/FAQ/FAQ.tsx
- apps/frontend/src/app/Components/Header/PublicHeader.tsx
- apps/frontend/src/app/Pages/PetOwner/PetOwner.css
- apps/frontend/src/app/Pages/PetOwner/PetOwner.tsx
- apps/frontend/src/app/Pages/PricingPage/PricingPage.css
- apps/frontend/src/app/Pages/PricingPage/PricingPage.tsx
> fix: Pricing Page Responsive & App added to Header

- apps/frontend/src/app/(routes)/organizations/page.tsx
- apps/frontend/src/app/Components/Header/Header.tsx
- apps/frontend/src/app/Components/Header/PrivateHeader.tsx
- apps/frontend/src/app/Components/Header/PublicHeader.tsx
- apps/frontend/src/app/Components/Header/UnverifiedProfile.tsx
- apps/frontend/src/app/Components/Header/VerifiedProfile.tsx
- apps/frontend/src/app/Components/ProtectedRoute.tsx
- apps/frontend/src/app/Pages/Organizations/Organizations.tsx
- apps/frontend/src/app/axios-services/services.ts
> fix: Fixed header bugs, converted cookie auth to header
